name: Java CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        run: ./gradlew build -x verifyGoogleJavaFormat
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binary
          path: build/libs
      - name: Generate test reports
        run: ./gradlew test jacocoTestReport
      - name: Upload code coverage report
        uses: actions/upload-artifact@v1
        with:
          name: coverage_report
          path: build/reports/jacoco/test/html
      - name: Upload test report
        uses: actions/upload-artifact@v1
        with:
          name: test_report
          path: build/reports/tests/test

  formatting:
    name: Verify formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      - uses: axel-op/googlejavaformat-action@v3.0.0
        with:
          args: "--aosp --dry-run --set-exit-if-changed"

  deploy:
    name: Deploy on Heroku
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download binary
        uses: actions/download-artifact@v2
        with:
          name: binary
          path: build/libs
      - run: ls -R
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.0.4
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "io-rpg"
          heroku_email: "hjaremko@outlook.com"
          usedocker: true
          docker_heroku_process_type: "web"
